name: Build

on: push

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.arch }} for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-18.04, windows-latest, macos-latest] # skip windows 
        os: [ubuntu-20.04, macos-10.15]
        arch: [auto, aarch64]
        exclude:
          - os: macos-10.15
            arch: aarch64

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1


      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.7.1

      - name: Build wheels
        env:
          CIBW_SKIP: "cp27-* cp35-* pp* cp36-manylinux_i686"
          CIBW_BEFORE_BUILD_LINUX: "/bin/bash cibuild/linux_steps.sh"
          CIBW_BEFORE_BUILD_MACOS: "/bin/bash cibuild/macos_steps.sh"
          # CIBW_TEST_COMMAND: "cd {project}/pyosmium/test && rm -rf ../build && python -m nose"
          # CIBW_BEFORE_TEST: "pip install nose mock shapely"

        run: |
          python -m cibuildwheel --output-dir wheelhouse pyosmium

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Test wheel 3.6
        if: ${{ matrix.arch != 'aarch64' }}
        run: |
          python --version
          python -m pip install nose mock shapely
          python -m pip install osmium --no-index --find-links file:///$(pwd)/wheelhouse/
          (cd pyosmium/test && rm -rf ../build && python -m nose)

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Test wheel 3.7
        if: ${{ matrix.arch != 'aarch64' }}
        run: |
          python --version
          python -m pip install nose mock shapely
          python -m pip install osmium --no-index --find-links file:///$(pwd)/wheelhouse/
          (cd pyosmium/test && rm -rf ../build && python -m nose)

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Test wheel 3.8
        if: ${{ matrix.arch != 'aarch64' }}
        run: |
          python --version
          python -m pip install nose mock shapely
          python -m pip install osmium --no-index --find-links file:///$(pwd)/wheelhouse/
          (cd pyosmium/test && rm -rf ../build && python -m nose)

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Test wheel 3.9
        if: matrix.os != 'macos-10.15' && matrix.arch != 'aarch64' # disabled because https://github.com/actions/virtual-environments/issues/2322
        run: |
          python --version
          python -m pip install nose mock shapely
          python -m pip install osmium --no-index --find-links file:///$(pwd)/wheelhouse/
          (cd pyosmium/test && rm -rf ../build && python -m nose)

      - name: Test wheel 3.8
        if: ${{ matrix.arch == 'aarch64' }}
        run: |
          docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
            ubuntu:20.04 \
            bash -exc 'apt-get update && apt-get -y install python3 python3-pip python3-venv && \
            python3 -m pip install virtualenv && python3 -m venv .env && \
            source .env/bin/activate && \
            python --version && \
            ls ./wheelhouse/ && \
            python -m pip install nose mock shapely && \
            python -m pip install osmium --no-index --find-links file:///$(pwd)/wheelhouse/ && \
            cd pyosmium/test && rm -rf ../build && python -m nose && \
            deactivate'

      - name: check wheel
        run: |
          ls ./wheelhouse/
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

